### ISSUE TITLE
Please use Github Pages to host these files directly on GitHub

### ISSUE THREAD

**Issue by joeytwiddle** [oldcompcz/jgs#2]
This would be much faster than archive.org

All you have to do is go into the GitHub repository's settings, and enable Github Pages using the `master` branch.

Then (in a few minutes) the collection should magically appear here:

https://oldcompcz.github.io/jgs/joan_stark

(I looked at `index.html` and it seems the links in there are relative, which is helpful.)

**Comment by joeytwiddle** [comment]
Hehe, already done!

**Comment by berk76** [comment]
Hello @joeytwiddle, you are right - this option is not much visible. So I have updated README.

Thank you and have a nice day.
